### PR TITLE
Add usage instructions about Button component on @expo/vector-icons

### PR DESCRIPTION
**Pull request by brunohkbx**
Instructions adapted from react-native-vector-icons

### CODE REVIEW

**Comment by brunohkbx** [comment]
AdamJNavarro could you please take a look?

**Comment by brunohkbx** [comment]
@AdamJNavarro  could you please take a look?

**Comment by AdamJNavarro** [comment]
Merging! Thanks for the PR, @brunohkbx.

**Comment by AdamJNavarro** [comment]
Hey Bruno, my apologies but there seems to be an error when building the docs with your PR. Could you test locally and let me know when you have fixed it?

**Comment by brunohkbx** [comment]
> Hey Bruno, my apologies but there seems to be an error when building the docs with your PR. Could you test locally and let me know when you have fixed it?

Hey @AdamJNavarro 
I forgot to put quotes around the curly braces in the example, sorry for that.
I also had to remove the sample image because there's a global style been applied to img tags  (max-width: 768px; width: 100%;) so I didn't found a way to properly render it without zooming the image.
What do you think?

**Comment by brunohkbx** [comment]
@ide the app is running fine locally. :smiley:

**Comment by brunohkbx** [comment]
@AdamJNavarro

**Pull request closed without merging**
