### PR TITLE
Update imagepicker.rst - add documentation for quality property

### PR DESCRIPTION
**Pull request by sbr464**
added property for quality in example, and added notes with example file sizes for the quality property based on iphone 7 file sizes/basic example

### CODE REVIEW

**Comment by sbr464** [comment]
I guessed at the defaults based on the results I found by leaving property undefined. Android/iOS seem to default to different values (1.0 and 0.1) if quality is not defined.

**Comment by brentvatne** [comment]
@nikki93 - can you look into improving image picker docs while you're working on improving image picker itself this cycle? 🙏

**Comment by brentvatne** [comment]
@nikki93 - what should we do with this docs PR?

**Comment by brentvatne** [comment]
Moved this to https://github.com/expo/expo/issues/163 so @nikki93 can make sure it's accurate

**Comment by nikki93** [comment]
Should see good docs for `quality` option in SDK 18!

**Comment by nikki93** [comment]
Released. 😮 🎊

**Pull request closed without merging**
