### PR TITLE
Small Typo Fix

### PR DESCRIPTION
**Pull request by BWillis98**

### CODE REVIEW

**Comment by brentvatne** [comment]
thanks. can you port this to the unversioned directory too?

**Comment by BWillis98** [comment]
I'll look into doing that right now. Not exactly sure how honestly, but I'll find it.

**Comment by BWillis98** [comment]
Should be good now @brentvatne !

**Comment by jimmylee** [comment]
@BWillis98 no apology necessary! Thank you so much :)

**Pull request closed without merging**
