### PR TITLE
Procedure and shortcuts for opening developer menu 

### PR DESCRIPTION
**Pull request by kstolte**
Adding Procedure and shortcuts because the image above on the page shows the developer menu but there is nothing on this page to assist with opening it.

### CODE REVIEW

**Comment by AdamJNavarro** [comment]
Hey @kstolte,

Some users may have switched their settings in the Expo Client from 'Shake device' to 'Two-finger force touch'. Could you add a note covering this case?

**Comment by kstolte** [comment]
Ill adjust

**Comment by kstolte** [comment]
@AdamJNavarro updated it with your advice regarding 'Shake device' to 'Two-finger force touch'. Tried to make it as clear as possible. Let me know if any other changes are needed.

**Comment by AdamJNavarro** [comment]
Hey @kstolte, sorry for the delay here. I feel like the current change is a little wordy. Thoughts on changing it to:

When in Development Mode, depending on your settings of the Expo Client, you will either shake your device or use a two-finger force touch to reveal the Developer Menu. When using an emulator, use the key command ⌘+D for iOS and Ctrl+M for Android.

**Comment by kstolte** [comment]
@AdamJNavarro all good. You guys are probably busy with Hacktoberfest and all. I liked your write up better. Good call. Implemented.

**Pull request closed without merging**
