### PR TITLE
Update imagemanipulator.md

### PR DESCRIPTION
**Pull request by wishfulthinkerme**
Hey,
just fix of the small typo.

Thanks!

### CODE REVIEW

**Comment by fson** [comment]
Hey, @wishfulthinkerme, thanks for the fix! Could you also make the change in `versions/unversioned/sdk/imagemanipulator.md`? That way it will be also included in the docs for future versions too.

**Comment by jimmylee** [comment]
@wishfulthinkerme let us know when you get those changes in!

**Comment by wishfulthinkerme** [comment]
@jimmylee Sorry for the delay. Done!

**Comment by jimmylee** [comment]
@wishfulthinkerme thank you so much :)

**Pull request closed without merging**
