### PR TITLE
ReactNative JSDoc import

### PR DESCRIPTION
**Pull request by fourcolors**
Hey everyone,

This PR includes ReactNative as a submodule to the ExpDocs. I'm doing this we can go to a specific version of ReactNative, generate .md files from their already existing JSdocs and then create a navigation .yaml file that gets used for ExpoUsers. This also has the ability to copy over all of the React Native Guides as they get created but I'm not doing that for now because it was cluttering the navigation up.

I'm running into a small snag when startup ExpoDocs as well so I guess this PR is a WIP until I resolve that. Here are the steps to get things working

1. Pull down all of the latest changes from React Native. Should be something like `git submodule update --recursive --remote`
2. Checkout the specific React Native version you want by navigating to the submodule and doing a `git checkout -b fooTag`
3. Run the generator via `yarn run import-react-native-docs`
4. Save save to the version you want with expo's built in helper tool `./scripts/versionpatch.sh unversioned v8.0.0 v7.0.0`
5. Startup ExpoDocs like normal with yarn start

I did have a few question about the project however.
1. I had to add some dependencies to the root package.json file which were already in the `./scripts/package.json` file. I feel like I'm doing something wrong here? How should I proceed?
2. Parsing of the .md files is breaking when generating the .html files for some reason. I'm still not sure why because my .md files are ast compatible. Anyone know why this might happen?
3. Would you like me to include the Facebook Guides? Or just the Component and API documentation?

### CODE REVIEW

**Comment by brentvatne** [comment]
@fourcolors - sorry for not replying, I've been away doing a workshop and emceeing React Europe! This is a pretty huge diff and I probably won't be able to review it until next week. cc @ccheever if you want to look

**Comment by fourcolors** [comment]
@brentvatne Hey, it's ok, I've been out last week trying to keep up with interview questions and such. I actually need to fix a few items on the PR and it also looks like there is a conflict of some sort. 

I'll try and get this wrapped up asap!

**Comment by fourcolors** [comment]
Oh and FYI most of those files are just generated files :p there is really one one or two files with "real" code in them.

**Comment by KyleAMathews** [comment]
How is the markdown parsing breaking exactly?

**Comment by fourcolors** [comment]
@KyleAMathews Well... it's been 11 days and apparently parsing isn't breaking? Anyway, this is the current issue

```
 TypeError: Cannot read property 'children' of undefined
[1]     at toString (/Users/sterling/Projects/expo-docs/gatsby/node_modules/mdast-util-to-string/index.js:36:14)
[1]     at extractId (/Users/sterling/Projects/expo-docs/gatsby/node_modules/gatsby-typegen-remark-expo-autolink/index.js:17:23)
[1]     at /Users/sterling/Projects/expo-docs/gatsby/node_modules/gatsby-typegen-remark-expo-autolink/index.js:61:14
[1]     at one (/Users/sterling/Projects/expo-docs/gatsby/node_modules/unist-util-visit/index.js:25:16)
[1]     at all (/Users/sterling/Projects/expo-docs/gatsby/node_modules/unist-util-visit/index.js:46:20)
[1]     at one (/Users/sterling/Projects/expo-docs/gatsby/node_modules/unist-util-visit/index.js:29:14)
[1]     at visit (/Users/sterling/Projects/expo-docs/gatsby/node_modules/unist-util-visit/index.js:14:3)
[1]     at module.exports (/Users/sterling/Projects/expo-docs/gatsby/node_modules/gatsby-typegen-remark-expo-autolink/index.js:60:3)
[1]     at /Users/sterling/Projects/expo-docs/gatsby/node_modules/gatsby-transformer-remark/extend-node-type.js:129:32
[1]     at Array.map (native)
[1]     at /Users/sterling/Projects/expo-docs/gatsby/node_modules/gatsby-transformer-remark/extend-node-type.js:126:55
[1]     at tryCatcher (/Users/sterling/Projects/expo-docs/gatsby/node_modules/bluebird/js/release/util.js:16:23)
[1]     at Promise._settlePromiseFromHandler (/Users/sterling/Projects/expo-docs/gatsby/node_modules/bluebird/js/release/promise.js:512:31)
[1]     at Promise._settlePromise (/Users/sterling/Projects/expo-docs/gatsby/node_modules/bluebird/js/release/promise.js:569:18)
[1]     at Promise._settlePromiseCtx (/Users/sterling/Projects/expo-docs/gatsby/node_modules/bluebird/js/release/promise.js:606:10)
[1]     at Async._drainQueue (/Users/sterling/Projects/expo-docs/gatsby/node_modules/bluebird/js/release/async.js:138:12)

```

I think I might have a blank file generated somewhere or a bad property in a yaml file. I'm looking into this now.

**Comment by fourcolors** [comment]
Ok, figured this out. I was generating some bad .md files. ie they have an empty `##` line ... yesh...  its those little things.

**Comment by fourcolors** [comment]
Alright, so I've been going down this path where I generate all of the docs from ReactNative's jsdocs which I thought was going to be a great idea, however they do some weird things with their JSDocs and it looks like they have a lot of custom styling and parsing to make everything work they way they want. 

Basically this means running it through a standard JSdocs parser doesn't make it look as nice but that latest push does work.

Does anyone have thoughts on what I should do from here? Options I've considered were.
1. Spin up the ReactNative website (somehow) locally then save their .html files inside of gatsby for each version we want. This would have the effect, hopefully, of more complete docs, however could run into CSS weirdness.
2. iFrame? This is kind of 😢  but could work, styling would be off but I think it wouldn't be quality work. 
3. Keep generating docs from RN and deal with the weirdness. Go to the RN project and fix how their docs work so this is no longer an issue. 

Option 3 assumes that RN doing funky things is an issue. 

Hopefully my thought process is clear? Thanks guys!

**Comment by abi** [comment]
Just had a chance to take a look at this, and run it locally. Great work, @fourcolors! I think the conversion from jsdocs -> md needs some more improvement. The biggest weirdness right now is that the sections for each component are ordered wrongly. The generated mds just follow the ordering of the js files, but on the React Native website, the ordering makes more sense. If we just fixed the ordering and added headers for each section, this is how our docs would look:

artboard 3

which, IMO, is good enough, and certainly useful to the average user of Expo.

Some other things to fix:

* Embedded images in RN docs
* Interactive code embeds
* Snack embeds

**Comment by KyleAMathews** [comment]
There's also a Gatsby plugin now for parsing JSDocs directly that handles the markdown conversion, etc. https://www.gatsbyjs.org/docs/packages/gatsby-transformer-documentationjs/

It's used several places on gatsbyjs.org e.g. https://www.gatsbyjs.org/docs/browser-apis/

There's also a transformer that wraps react-docgen https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-react-docgen

**Comment by abi** [comment]
Thanks for your work here, @fourcolors! We are going to do the cleaner approach of using the docgen output directly and transforming that with `gatsby` plugins.

**Pull request closed without merging**
