### PR TITLE
Update filesystem.md to reflect need to update documentDirectory path for cached values

### PR DESCRIPTION
**Pull request by dereknelson**
Changed the following: 
>`file://` URI pointing to the directory where user documents for this app will be stored. Files stored here will remain until explicitly deleted by the app. Ends with a trailing `/`. Example uses are for files the user saves that they expect to see again.

->
>`file://` URI pointing to the directory where user documents for this app will be stored. Files stored here will remain until explicitly deleted by the app. Ends with a trailing `/`. Example uses are for files the user saves that they expect to see again. Note, when users update the app via their respective app store, the documentDirectory path will also be updated, so any cached files will need the latest path. Best practice is to append your filepath to the document directory at runtime.
  Example: 
  ```
  import { FileSystem } from 'expo'
  const folder = `${FileSystem.documentDirectory}yourPath`;
  const file = 'someImage.jpg'
  const filePath = `${folder}/${file}`;
  ```

### CODE REVIEW

**Comment by jimmylee** [comment]
@dereknelson sorry about the delay and thank you for your help. Can you rebase your PR?

**Comment by dereknelson** [comment]
@jimmylee pretty sure I rebased it, but this is also my first pr so you may want to verify haha

**Comment by jimmylee** [comment]
Hey @dereknelson some of the commits such as Eric's shouldn't be in this PR. And there is a change to `yarn.lock` and `package.json` that would be nice to be taken out.

**Comment by jimmylee** [comment]
I haven't seen an update in a while, I'm going to close this PR and ask you to open a new one. Sorry about the inconvenience. It'll probably be easier for you to just make a fresh PR with your changes.

**Pull request closed without merging**
