### PR TITLE
default value of fallbackToCacheTimeout should be 0

### PR DESCRIPTION
**Pull request by chunghe**

### CODE REVIEW

**Comment by jimmylee** [comment]
Hey @chunghe thanks a bunch :-), could you update this in `unversioned` as well?

**Comment by chunghe** [comment]
sure. done.

**Comment by jimmylee** [comment]
@chunghe you are my hero! Thank you!

**Comment by esamelson** [comment]
This is actually wrong -- the default value (meaning the value used if the key is not specified at all in app.json) is indeed 30000, so I'm going to ahead and revert this commit.

**Pull request closed without merging**
