### PR TITLE
Add documentation for universal/deep links and Android intent filters

### PR DESCRIPTION
**Pull request by schneidmaster**
* Adds documentation for Android intent filters in the `app.json` (added in https://github.com/expo/xdl/pull/30)
* Adds documentation for iOS Universal Links (they seem to already work out-of-the-box and I'm using them in production, but there wasn't really any documentation other than the link to the Branch feature)
* Adds documentation for Android intent filters/using intent filters for deep linking on Android

Note that this documentation assumes https://github.com/expo/xdl/pull/32 has been merged -- there was a bug on the original PR where the schema validation does not allow an intent filter's `data` to be an array (even though the code works with either an object or an array)

### CODE REVIEW

**Comment by schneidmaster** [comment]
No problem, thanks @jimmylee!

**Comment by jimmylee** [comment]
@schneidmaster looks like there is a merge conflict 🐙

**Comment by schneidmaster** [comment]
@jimmylee I see SDK 30 just dropped, should I update my PR to add the docs for 30 + unversioned (instead of 29 + unversioned)?

**Comment by jimmylee** [comment]
You rock, thank you @schneidmaster !!

**Comment by jimmylee** [comment]
I can't wait to land this when https://github.com/expo/xdl/pull/32 merges.

**Comment by jimmylee** [comment]
@schneidmaster @fson looks like the PR moved, can you guys update me on when this is good to land?

**Comment by schneidmaster** [comment]
@jimmylee We've reopened our PR at https://github.com/expo/expo-cli/pull/46, will keep an eye out and let you know when it gets merged.

**Pull request closed without merging**
