### PR TITLE
Description of MINIMUM permissions (app.json)

### PR DESCRIPTION
**Pull request by danikane**
Add a list of the minimum necessary permissions when "permissions": [] is set.

### CODE REVIEW

**Comment by jimmylee** [comment]
@danikane this is awesome! Please add this to `unversioned` as well and I'll be able to land it :)

**Comment by danikane** [comment]
Sure, sorry about the delay. :)

**Comment by brentvatne** [comment]
🔥

**Comment by jimmylee** [comment]
Amazing, like usual! Thanks

**Pull request closed without merging**
