### PR TITLE
Add v24 and v25 to Upgrading Expo

### PR DESCRIPTION
**Pull request by evert-smit**
Make sure the latest release notes are in the list. Also clarify that the example mentioned in the description is the latest post.

### CODE REVIEW

**Comment by evert-smit** [comment]
I just noticed I'm the fourth person to make a pull request like this. Is there a reason why this change can't be added? It was kind of confusing to me coming back to Expo since some time and then first upgrading to v23, then noticing v25 is already available.

**Comment by jimmylee** [comment]
@evert-smit you're totally right about this! I'm sorry it took so long to address you.

**Comment by jimmylee** [comment]
In the future, I'm going to start making it an effort to check these pull requests every day. It turns out we've already landed the update so I'm going to close this.

@evert-smit I'm really sorry about the delay. And I appreciate the fact that you went to submit a pull request.

**Comment by evert-smit** [comment]
@jimmylee No problem, thanks!

**Pull request closed without merging**
