### PR TITLE
Fix mimetype image/jpg to image/jpeg

### PR DESCRIPTION
**Pull request by xcarpentier**

### CODE REVIEW

**Comment by abi** [comment]
Merged into the main repo. Will show up on the docs site shortly. Thanks for your contribution!

**Comment by abi** [comment]
It's the internal repo, once it's pushed onto master there, our bot will copy it over to this repo.

**Comment by xcarpentier** [comment]
Ok thanks,
BTW Is it the same with all Expo repo?

**Comment by abi** [comment]
Yup, https://blog.expo.io/universe-exponents-code-base-f12fa236b8e

**Pull request closed without merging**
