### PR TITLE
Building standalone apps - add additional steps for ios

### PR DESCRIPTION
**Pull request by peterpme**

### CODE REVIEW

**Comment by peterpme** [comment]
I did this super early today and it could be wrong. A review would be helpful otherwise I'll review over the next day :) Thanks!

**Comment by peterpme** [comment]
@brentvatne if you don't mind reviewing, this is good to go! Thanks

**Comment by peterpme** [comment]
@abi mind taking a look at this one too while you're at it? Thanks!

**Comment by abi** [comment]
This is great! Merging it in.

**Pull request closed without merging**
