### PR TITLE
Updated getInfoAsync return values

### PR DESCRIPTION
**Pull request by sameesiddiqui**
* added isDirectory as a return value
* slightly reordered list to the order in which they occur when returned

### CODE REVIEW

**Comment by abi** [comment]
Hey @sameesiddiqui can you also copy the changes to the `unversioned` docs?

**Comment by sameesiddiqui** [comment]
@abi sure, done

**Comment by sameesiddiqui** [comment]
@abi anything else I need to do here?

**Comment by abi** [comment]
No, I only get around to merging all these PRs once a week :P Merging now.

**Pull request closed without merging**
